### ISSUE TITLE
Example no longer builds in sandbox-mode with the current state of the basement layer(s).

### ISSUE THREAD

**Issue by sbixl** [BobBuildTool/bob-example-embedded#3]
Hi,

I tried to build the example with the current state of the basement and basement-gnu-linux layers. Unfortunately, building in the sandbox fails. When comparing the commits, I noticed that changes were made to the sandbox regarding the toolchain and the sandbox itself. 

Do adjustments have to be made in the example (set the correct toolchain or something similar) or is there something fundamentally wrong here? 

If you can give me a hint, I can try to adjust the example including PR. :-)

**Comment by sbixl** [comment]
Did some more research and the problem occurred the first time, moving to commit [8131cf1](https://github.com/BobBuildTool/basement/commit/8131cf11b5d99b1804e1de5eaccb75ce3d9cc735) of the `basement layer`.  For the `basement-gnu-linux layer` commit [c9ed7d3](https://github.com/BobBuildTool/basement-gnu-linux/commit/c9ed7d30bc836810cab7e557bc0bb44c70036172) must be used in this case. 

The library `elfutils` which is part of the `basement-gnu-linux layer` fails when building. The root cause seems to be a [problem](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=104069) with GCC 12.2.0. 

I investigate it further...

**Comment by sbixl** [comment]
After doing the following modifications in the current master state of the `basement-gnu-linux layer`:

- bump elfutis to version 0.190
- bump Linux kernel to version 6.1.72

the example project is building fine again if I use commit [38c2362](https://github.com/BobBuildTool/basement/commit/38c2362fdcde235b23ec73cfd96124bee3fba628). 
But if i switch to the next commit [8131cf1](https://github.com/BobBuildTool/basement/commit/8131cf11b5d99b1804e1de5eaccb75ce3d9cc735) the build fails with the following output:

  CC       elf_compress_gnu.os
  AR       libelf.a
  AR       libelf_pic.a
  CCLD     libelf.so
/toolchain/lib/gcc/x86_64-bob-linux-gnu/12.2.0/../../../../x86_64-bob-linux-gnu/bin/ld: /bob/d633f26c87db1e949109ded4f7ddd1a5577fe896/workspace/usr/lib/libz.a(deflate.o): relocation R_X86_64_32S against hidden symbol `_length_code' can not be used when making a shared object
/toolchain/lib/gcc/x86_64-bob-linux-gnu/12.2.0/../../../../x86_64-bob-linux-gnu/bin/ld: failed to set dynamic section sizes: bad value
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:1353: libelf.so] Error 1
make[1]: *** [Makefile:537: all-recursive] Error 1
make: *** [Makefile:453: all] Error 2
Step failed with return status 2; Command: make -j "${MAKE_JOBS-$(nproc)}" "$@"
Call stack (most recent call first)
    #0: Class  make, layer basement, line 9, in makeParallel
    #1: Class  autotools, layer basement, line 71, in autotoolsBuild
    #2: Recipe libs::elfutils#1, layer basement-gnu-linux, line 3, in main
Build error: ./work/libs/elfutils-libelf-dev/x86_64-bob-linux-gnu/build/3/build.sh returned with 2
Failed package: demo::linux+freertos/demo::vexpress/kernel::linux-image/libs::elfutils-libelf-dev
You may resume at this point with '--resume' after fixing the error.

The elfutils do not support the disable-shared as well es enable-static option in the configure step. I tried the following [patch](https://sourceware.org/bugzilla//attachment.cgi?id=12670) without any success.

Any idea how to fix this?

**Comment by jkloetzke** [comment]
Can you test with the current basement head? Commit [8131cf1](https://github.com/BobBuildTool/basement/commit/8131cf11b5d99b1804e1de5eaccb75ce3d9cc735) is known to be bad. You need to go at least to 6623751428 that fixes some serious library building issue...

**Comment by sbixl** [comment]
I had already tried this at the very beginning with a similar error. I then tried to narrow down the cause further to find the point where it had stopped working. With the above mentioned adjustments I get the same error even with the current basement head.

**Comment by jkloetzke** [comment]
I see. :confused:  Could you maybe provide the latest state as branches in your forks so that I can try it out myself?

I think we falsely used the host zlib (the one from the build host or the sandbox image) when building elfutils. Clearly, the root cause is that elfutils tries to build a shared library. That must be prevented because even if it succeeds, building shared libraries against static library dependencies calls for trouble.

**Comment by sbixl** [comment]
Sure, i pushed my changes her:

1. https://github.com/sbixl/basement-gnu-linux/tree/work/update_elfutils
2. https://github.com/sbixl/bob-example-embedded/tree/work/update_layers
3. https://github.com/sbixl/basement/tree/work/update_layers

PS: [2] is still referencing the official git submodul of the basement-gnu-linux layer.

The modifications regarding the update of the Linux kernel I have not yet added. It was a downstream problem of my investigations so maybe the problem is gone and the current kernel compiles fine after the problem with the eltutils were fixed. The problem with the kernel was that it could not find the header mpc.h. According to some short research on the net, this was a problem in the 5x kernel. After an update to 6x the problem was gone.

As far as I understand the elfutils buildflow correctly, there is no way to prevent the additional building of the shared library. If the build works again, it may be enough to simply not copy the lib into the packageStep?

**Comment by jkloetzke** [comment]
The primary problem is that all dependency tool remappings like the following:

```yaml
depends:
    - tools:
        target-toolchain: host-toolchain
```

need to be changed to

```yaml
        target-toolchain: host-compat-toolchain
```

BUT, this only partially fixes it. I guess this is due to the fact that the host-compat-toolchain is based on gcc 7 whereas the host-compiler is using gcc 12. The proper solution is to patch libelf to *not* build shared libraries on host builds...

**Comment by sbixl** [comment]
Ok thanks for the hint! I will try to find a way to patch libelf not building the shared libraries.

**Comment by sbixl** [comment]
Hi,

i tried to fix the problem using the latest HEAD of the basement project but still get trouble while building the basics (see
[build_error.txt](https://github.com/BobBuildTool/bob-example-embedded/files/14229067/build_error.txt)).

I am also surprised that nothing is downloaded from the binary archive.

Any idea what is the problem here?

**Comment by jkloetzke** [comment]
I'll look into it in the evening.

The broken downloads are caused by a Bob bug in the mirror feature that is already used on ci.bobbuildtool.dev. I have a preliminary fix that needs some finishing touches still...

**Comment by jkloetzke** [comment]
I could reproduce the issue. I think this may be related to some autoconf issue but I'm not sure. Somehow `src/config.h.in` managed to be older than `aclocal.m4`. The timestamps of the former were strangely rounded down to a second. Re-running autoreconf made the issue go away. I guess it's pure luck to hit the error or not.

**Comment by jkloetzke** [comment]
I think I found the underlying issue. See BobBuildTool/basement#195. Unfortunately it triggers an almost complete rebuild.

> I am also surprised that nothing is downloaded from the binary archive.

That issue should be resolved too by now.

**Comment by sbixl** [comment]
I scheduled a complete rebuild including [BobBuildTool/basement#195](https://github.com/BobBuildTool/basement/pull/195) and the current head of bob for testing. Let's see how it performs on my side! ;-)

After doing some minor modifications in the recipes,  the example is building fine again in sandbox mode using the latest head of bob. Downloading from the binary archive works like a charm  so that I am able to build the example in a few minutes! :-)

The problem regarding libelf is gone after switching to `host-compat-toolchain`. In the background the shared library is still being built but not copied by the install classes. So I am not sure whether it is worth the effort to solve the problem to prevent the building of the shared library in host builds? 

I will now prepare the required PR to bump the example project to the latest heads of the layers. I think it would also make sense to update the minimal required version of bob to the upcoming 0.24, so that no one else will stumble across the problem in future.

**Comment by sbixl** [comment]
I think you can merge PR#195.

The problem no longer occurs. It was always reproducible in my environment before.

**Comment by jkloetzke** [comment]
> After doing some minor modifications in the recipes, the example is building fine again in sandbox mode using the latest head of bob. Downloading from the binary archive works like a charm so that I am able to build the example in a few minutes! :-)

Nice. Thanks for testing.

> I will now prepare the required PR to bump the example project to the latest heads of the layers.

:+1: 

> I think it would also make sense to update the minimal required version of bob to the upcoming 0.24, so that no one else will stumble across the problem in future.

That should not be necessary. The root cause for the download problems was related to some deficiencies in the new mirrors feature. I used the basement CI as a test-bed and it revealed some smaller design issues. After fixing these, the artifacts were created correctly now. For someone who builds projects and expects to receive pre-built artifacts, the fixes in Bob are not relevant.

**Comment by sbixl** [comment]
First the [PR#14](https://github.com/BobBuildTool/basement-gnu-linux/pull/14) for the `basement-gnu-linux` needs to be merged before I can set the final PR for this project.

You can find my current state of work [here](https://github.com/sbixl/bob-example-embedded/tree/work/update_layers). (only the commit for the update of the `basement-gnu-linux` layer is missing.
